### ISSUE TITLE
Users can create and send a new text message to a client

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#10]
**User story:**
- As a PO
- I want to send a text message to my client
- So that I can reach him/her quickly
 
**Requirements:**
- Twilio API integration
- PO can send a message from the message stream
- If message can’t be delivered, show “Undelivered - Error” status in message stream next to message
- Desktop designs: https://invis.io/4GBODKTUN#/233336018_message_Stream_A_-_Responding, https://invis.io/4GBODKTUN#/233336017_message_Stream_A_-_Typing, https://invis.io/4GBODKTUN#/233336016_message_Stream_A_-_Sent

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.vwc6xcw5jfws

**Comment by tmaybe** [comment]
design isn't complete, but this is functionally done as of d045e1449c6d9c620a76e142695d500ce94476a8
