### ISSUE TITLE
Unclaimed messages go to ClientComm’s PO account (P2)

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#13]
**User story:**
- As a client with a new phone number
- I want to be able to text message my PO
- So that I can continue communicating with him/her
 
**Requirements:**
- When we receive a text from a client and there is no match to an existing client, we should (1) Create new client in db (no name or DOB, just phone number) and (2) Attach client to ClientComm’s PO account
- If ^ happens, ClientComm product team will be able to text with the client to determine who the right PO is. Once we determine the correct PO, we’ll transfer the client through the database (no user-facing functionality) and manually alert the PO that they have a new client/message. 
- Note that this isn’t an ideal long-term solution, but is a temporary band-aid so that we don’t have any messages that fall through the cracks.

<img width="401" alt="screenshot 2017-07-19 13 42 10" src="https://user-images.githubusercontent.com/5083453/28388628-386c6518-6c88-11e7-9107-e3c51d82c939.png">

<img width="289" alt="screenshot 2017-07-19 13 43 02" src="https://user-images.githubusercontent.com/5083453/28388629-38741754-6c88-11e7-8cab-796951b8ae29.png">

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.joo6wm1qhamx

**Comment by tmaybe** [comment]
Noting that the "ClientComm PO account" should be the equivalent of an "owner" account, with a flag in the database, so the application knows where to send unclaimed messages.

**Comment by cweems** [comment]
* Create default account for unclaimed messages when a user starts
* Add logic to route unclaimed users to specified account
* Add documentation about how to transfer a client
