### ISSUE TITLE
Finish implementing Mixpanel tracking (P1)

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#15]
**User story**
- As a product manager
- I want to analyze how users are using ClientComm
- So that I can assess how the product is doing without needing engineering resources

**Requirements**
Implement Mixpanel on the MVP, using [this taxonomy](https://docs.google.com/spreadsheets/d/1a8xhUjOxdyPavKbJRWZWe43WUMaolIwiN25zEXM-O9E/edit#gid=452228794)

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.1i0tarylbxy0

**Comment by tmaybe** [comment]
renamed to reflect that we've implemented all the events in the taxonomy except `message_alert`, `message_alert_click`, and a new one I added, `message_send_failed`. Moving this issue back into "To Do" for re-prioritization.
