### ISSUE TITLE
CC Admins can invite users (P2)

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#17]
**User story**
- As a ClientComm team member
- I want to invite users to join ClientComm
- So that the only people who use ClientComm are people we've approved

**Requirements**
- Get rid of 'sign up' option on main /login screen
- When we want to add a new user, we give their email address to @tmaybe. He will create a user account manually in the db. We will then send the user through the [forgot password flow](https://try.clientcomm.org/users/password/new) to create a new password and account. 

@tmaybe does that work for you, or was there more you wanted to set up?

**Comment by tmaybe** [comment]
I think an easier step one would be to require an invite code when submitting the Sign up form–something we hard-code into the app. Step two would be implementing email invitation functionality with [devise invitable](https://github.com/scambra/devise_invitable).
