### ISSUE TITLE
ClientComm 1.0 responsive styleguide

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#2]
**User story:**
- As a PO on the go
- I want to use ClientComm from different devices
- So that I don’t have to be sitting at my computer in order to send messages
 
**Requirements:**
- Use [GCF styleguide](https://getcalfresh.org/styleguide)

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.gnpb69au151c

**Comment by tmaybe** [comment]
Imported as of 5819e7d1af2fd57300f451b08902928404ebfb2c and configured/tweaked in subsequent commits.
