### ISSUE TITLE
fix the top bar in place

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/clientcomm-rails#24]
I think the top bar (or a minimized version of it) should be fixed. When there are a lot of messages, it takes a while to scroll to the top so you can navigate off the page.

![better-scrolling](https://cloud.githubusercontent.com/assets/546665/26742262/d6f59608-4791-11e7-95f1-b6bbbe71e88b.gif)

**Comment by racheledelman** [comment]
this still seems worth doing.

**Comment by alsomanya** [comment]
Moved to Pivotal, closing.
