### ISSUE TITLE
figure out a way to integrate intercom into the messages page

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/clientcomm-rails#25]
There's not a lot of room for the Intercom widget on the messages page. Right now we've disabled it on that page. Is there a way to keep it in that doesn't crowd our interface?

<img width="130" alt="screen shot 2017-06-01 at 7 44 30 pm" src="https://cloud.githubusercontent.com/assets/546665/26742306/1dd291c0-4792-11e7-8221-2c040ae4c74f.png">

**Comment by alsomanya** [comment]
Moved to Tracker
