### ISSUE TITLE
make message bubbles shrink to fit short text

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/clientcomm-rails#26]
It'd be nice if both outgoing and incoming bubbles shrunk to fit short text:

<img width="777" alt="screen shot 2017-06-01 at 7 46 08 pm" src="https://cloud.githubusercontent.com/assets/546665/26742393/59122e62-4792-11e7-9fce-697fb88c57c2.png">

**Comment by alsomanya** [comment]
done with #76
