### ISSUE TITLE
Users can see that there are pending messages in a message stream

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#48]
- [ ] HTML/CSS for the alert complete
- [x] submitting the form results in a flash banner confirmation message that message has been scheduled
- [x] an alert above the _send message_ form on a client's message index indicates the number of scheduled messages set for that client

**User story**
- As a case manager
- I want to see which messages I’ve scheduled for later with a client
- So that I can keep track of what’s going out to them and make changes

**Notes**
- For now, even if there's only one message scheduled, user should go to message index modal and then into message edit modal. While this UX isn't ideal, we want to get the functionality out the door ASAP and not add complexity.

**Design**
- Desktop: [pending message notification](https://invis.io/AQC9OPBEH#/240140264_6_Scheduled_Text_-_Pending_Text_-_Desktop), [message index](https://invis.io/AQC9OPBEH#/240140265_7_Scheduled_Text_-_Message_List_-_Desktop)
- Mobile: [pending message notification](https://invis.io/Z7C9OQ9X3#/240140460_4_Scheduled_Text_-_Pending_Text_-_Mobile), [message index](https://invis.io/Z7C9OQ9X3#/240140461_5_Scheduled_Text_-_Message_List_-_Mobile)

**Comment by tmaybe** [comment]
- [ ] [code link](https://github.com/codeforamerica/clientcomm-rails/pull/83/files#diff-eba21d978883d7d2010ed3830d9564b7R18) -- consider migrating all send_at fields to be equal to created_at when send_at is NULL, then order by send_at 
- [ ] [this code](https://github.com/codeforamerica/clientcomm-rails/pull/83/files#diff-a9d7494a78fbcb4d7beec822b2b3f885R40) is messy, I think we should clean this up in general but this does not block the current story.
- [x] [this](https://github.com/codeforamerica/clientcomm-rails/pull/83/files#diff-eba21d978883d7d2010ed3830d9564b7R68) should be a flash message, and not broadcast a notification

**Comment by tmaybe** [comment]
- [x] the alert/link should update live when scheduled messages are created and sent

**Comment by zaksoup** [comment]
- [x] make sure to add back in test for `scheduled_message_job` that we accidentally deleted
