### ISSUE TITLE
Users can edit pending messages

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#49]
- [ ] HTML/CSS for the scheduled message edit form complete
- [ ] in the scheduled message index, there's an edit icon next to each message
- [ ] clicking the edit icon loads a form to edit the text, date, and time of the scheduled message
- [ ] making an edit and submitting the form changes the scheduled message in the database
- [ ] a delete button on the form deletes the message
- [ ] validation/error states from #51 apply to this form as well
- [ ] upon making edits, user returns to message stream and receives a confirmation banner

**User story**
- As a case manager
- I want to edit when a message will be sent
- So that I can still remind clients about appointments, even if those appointments change

**Notes**
- Confirmation banner text: Your message has been updated.

**Design**
- Desktop: [message index](https://invis.io/AQC9OPBEH#/240140265_7_Scheduled_Text_-_Message_List_-_Desktop), [edit modal](https://invis.io/AQC9OPBEH#/240140266_8_Scheduled_Text_-_Update_Message_-_Desktop), [confirmation](https://invis.io/AQC9OPBEH#/240140267_9_Scheduled_Text_-_Update_Confirmation_-_Desktop_Copy)
- Mobile: [message inde](https://invis.io/Z7C9OQ9X3#/240140461_5_Scheduled_Text_-_Message_List_-_Mobile)x, [edit modal](https://invis.io/Z7C9OQ9X3#/240140462_6_Scheduled_Text_-_Update_Messages_-_Mobile), [confirmation](https://invis.io/Z7C9OQ9X3#/240140463_7_Scheduled_Text_-_Update_Confirmation_-_Mobile)

**Comment by racheledelman** [comment]
Small update on the manage scheduled messages flow: in the editing phase of the modal, we want to add a back button. This will let you return to your list of scheduled messages.

![back button.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a2c1d4a9135c1300017b57/125516c66e82c728ace21e0d46ea959928c281bc9bfdb04de611b2843b492d762a10e17132d0bb7ebc1379055c0a1ff9155f5d12f4f9892ef4b03b79824e17ff933c0120996048e6edc00db513b921814e81bfb58d4fc3ee3f2de38c8f5d73.png)

**Comment by tmaybe** [comment]
- [ ] link between scheduled message and related delayed job so that date/time can be edited
- [ ] We need to add a column to Messages to point to the `provider_job_id` of the delayed job so that when the user edits the send_at we can delete and recreate the Active Job with the new time
