### ISSUE TITLE
Users have accounts on ClientComm 1.0

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#5]
**User story:**
- As a PO
- I want to have an account on ClientComm
- So that I can use the app to communicating with my clients
 
**Requirements:**
- Create user database
- We manually create accounts (name, email address, passwords) in the database for now
- No user ‘types’ - just POs, everyone has all functionality

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.3kn5yopjv7dn

**Comment by tmaybe** [comment]
Closed with 6c4fe6355a76f306f9bf9552c06286cc42b216f3
