### ISSUE TITLE
Users can delete pending messages

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#50]
- [ ] HTML/CSS for the scheduled message index complete
- [ ] the alert above the _send message_ form links to a scheduled message index for that client
- [ ] the scheduled message index shows a list of scheduled messages, each with a snippet of the message text, the send date, and a _delete_ link or icon.
- [ ] clicking the _delete_ link or icon deletes the associated scheduled message and reloads the scheduled message index

**User story**
- As a case manager
- I want to delete pending scheduled messages
- So that if an appointment is cancelled, a client won’t be confused with a reminder

**Notes**
- Confirmation banner text: "Your message has been deleted."

**Design**
- [Desktop](https://invis.io/AQC9OPBEH#/240140266_8_Scheduled_Text_-_Update_Message_-_Desktop)
- [Mobile](https://invis.io/Z7C9OQ9X3#/240140462_6_Scheduled_Text_-_Update_Messages_-_Mobile)

**Comment by tmaybe** [comment]
Hey @alsomanya, I restored the flow that doesn't require the edit modal. In order to keep the issues describing discrete chunks of functionality that can be made live, I thought it'd be a good separation to implement the scheduled message index in this issue (with temporary _delete_ links) and the edit modal in #49, when it's needed.

**Comment by alsomanya** [comment]
@tmaybe that makes sense; when we implement #49 (or after we implement) can we then go back and change the message index so it only has an edit button? My worry is having too many action buttons in that index will make the UI cluttered, but I'm fine to sequence that later.

**Comment by tmaybe** [comment]
@alsomanya yep, absolutely; we'll swap out the delete button for an edit button.
