### ISSUE TITLE
Users can create scheduled messages

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/clientcomm-rails#54]
- [x] redesign _send message_ form to add a 'send later' button (HTML/CSS)
- [x] clicking 'send later' opens a modal where user can see the message and select when the message will be sent
- [x] in modal, users can edit message text and choose date and time
- [x] submitting the form creates a scheduled message
- [x] submitting the form results in a flash banner confirmation message that message has been scheduled
- [x] canceling the form returns user to message page with draft message still in input field
- [x] the scheduled message is sent on the set date (test coverage)
-  ~~when the scheduled message is sent, it appears in the client's message index (described in #48)~~

**User story**
- As a case manager
- I want to be able to send a message in the future
- So that I can remind clients about upcoming appointments and events

**Notes**
- For now, use PST as the time zone
- User can select date via a date-picker
- User can select time via a time dropdown

**Design**
- Desktop design: [scheduling message](https://invis.io/AQC9OPBEH#/240140259_2_Scheduled_Text_-_Schedule_Modal_-_Desktop), [choosing date](https://invis.io/AQC9OPBEH#/240140261_3_Scheduled_Text_-_Date_Modal_-_Desktop), [choosing time](https://invis.io/AQC9OPBEH#/240140263_5_Scheduled_Text_-_Time_Modal_-_Desktop), [confirmation](https://invis.io/AQC9OPBEH#/240140264_6_Scheduled_Text_-_Pending_Text_-_Desktop)
- Mobile design: [scheduling message](https://invis.io/Z7C9OQ9X3#/240140458_2_Scheduled_Text_-_Schedule_Modal_-_Mobile), [confirmation](https://invis.io/Z7C9OQ9X3#/240140460_4_Scheduled_Text_-_Pending_Text_-_Mobile)

**Comment by tmaybe** [comment]
closed with #69 ... moving the un-checked task to #48

**Comment by alsomanya** [comment]
After talking with @zaksoup, moving this back to implementation. There are a few blocking and non-blocking UX issues @racheledelman and I found before this is considered done, [documented here](https://docs.google.com/document/d/1LCiUmtDZlwumQILK7gDA9ulcLdqt-rDRA98DuoBL6is/edit#). 

- [ ] "Send" and "Send later" buttons shouldn't be hidden at small screen sizes (blocking)
- [ ] Implement date and time picker, per Invision designs (linked in original ticket above) (blocking)
- [ ] Decrease modal height (blocking)
- [x] Implement flash banner confirmation when message gets scheduled (in progress) (blocking)
- [ ] Remove icons on "send" and "send later" buttons (non-blocking)
- [ ] Ensure modal uses GCF's styleguide and modal header is an H1 or H2 per Invision designs (non-blocking)
