### ISSUE TITLE
Sending pictures not working from Go-Phones

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#56]
I tried sending pictures to the ClientComm `try` number through our new GoPhones — a Samsung Galaxy Express 3 and an LG flip phone. I'm not sure why they aren't working but I got error messages on both when I tried to send a picture.

**Notes**
- Samsung phone is connected to wi-fi, but I'm not sure if it's using wifi or the cellular network to send. 
- LG phone is cell network only.
- Sending written texts works on both, so it doesn't seem like it's a network problem? Not sure how MMS works vs SMS, and why one isn't working but the other is...

**Comment by tmaybe** [comment]
What were the error messages you got?

**Comment by alsomanya** [comment]
Error messages just said "Unable to send message to ClientComm" or "Sending failed"

**Comment by tmaybe** [comment]
Not a clientcomm error.
