### ISSUE TITLE
Users can log into and out of ClientComm

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#6]
**User story:**
- As a PO
- I want to log into and out of ClientComm
- So that I can use the app securely
 
**Requirements:**
- Users need to log into ClientComm to use it from a login page
- Indefinite session length for now
- Users can log out from any screen of the app
- Desktop design: https://invis.io/4GBODKTUN#/233332891_Log_In
- Mobile design: https://invis.io/2RBODOFKP

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.5vipggy7kz9v

**Comment by tmaybe** [comment]
done as of aaf51d27c437623d13e5b87d11ce39e0bd888bdd
