### ISSUE TITLE
Users can add clients

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#7]
**User story:**
- As a PO
- I want to add and save my clients to ClientComm
- So that I can easily and quickly send them messages 
 
**Requirements:**
- Clients get stored to db and matched with corresponding PO
- Client info stored: name, phone number, DOB
- Users cannot add multiple contact methods for clients for now. If clients have multiple contact methods, they will have to create multiple clients. 
- Desktop design: https://invis.io/4GBODKTUN#/233336020_Add_Client
- Mobile design: https://invis.io/YGBODLCTQ#/233333623_Mobile_Add_Client

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.gfuy5hdyp49v

**Comment by tmaybe** [comment]
Done as of 1917b7966a76fa75f617d5ba0fbde0d6bd582c11

There's no concept of a PO yet, but when we add user accounts in #5 and #6 we'll make that association.
