### ISSUE TITLE
Users can download transcripts

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#75]
**User story**
- As a case manager
- I need to download transcripts of messages with clients
- So that I can save my messages and share them with others

**Requirements**
- Change 'edit client' button on message stream to 'manage client'
- Clicking that button takes user to edit client page, which now also includes a "manage" section (see design below)
- Manage section has download transcript button
- Downloading transcript functionality works the same as on original (node) ClientComm - clicking button downloads .rtf file

**Design**

![68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3536613263316434613931333563313330303031376235372f313235353136633636653832633732386163653231653064343665](https://user-images.githubusercontent.com/5083453/28096114-39f77ee6-665b-11e7-96bc-f21f3082d13e.png)

**Comment by racheledelman** [comment]
Two variations. Also, we'll want to hide this button on mobile.
![download transcript.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a2c1d4a9135c1300017b57/125516c66e82c728ace21e0d46ec9b8d2d8e8ca88ba9ab51a553e3973b4f37676b48e13b628ae92dbc56395b4d5a46aa12590d10ffacd87ef2b13e26825c0be8836b587dce2f0dbefad341eb5ee779c11ac7a4b6984ec6e23c21ee82884d3a18011b8dfc5527ed.png)

![download transcript2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a2c1d4a9135c1300017b57/125516c66e82c728ace21e0d46ec9b8d2d8e8ca88ba9ab51a553e3973b4f37677b46ef696097ec22ba416f43554d4ba4470b5e16a8fadc7af3e23b72dc540bedd43f5973cf3503b0aac04ee155e57dd205d0f4ae805ec3e93724e38286483c18041b8cf75a31b2d4.png)

This is a pretty secondary action, so we should think about how prominent we want to make it. We could move this action to the "edit client" page, which would make it more of a "manage client" page.

**Comment by alsomanya** [comment]
Oh, I like the idea of changing the button to "manage client" and putting this in there! That makes sense to me, since this action won't be used frequently and doesn't need to be super prominent (but does need to be accessible when a case manager needs it).

**Comment by racheledelman** [comment]
Here's what a "manage client" page with a transcript download button could look like. The single button looks a little silly, but eventually we can add more actions to that card (status, archive, etc). Also, if we eventually wanted to add date range specification or anything to transcripts, we have some room to spread out.
 
![download transcript3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a2c1d4a9135c1300017b57/125516c66e82c728ace21e0d46ec9b8d2d8e8ca88ba9ab51a553e3973b4f37677a46ef696097ec22ba416f43554d4ba4470b5e16a8fadc7af3e23b72dc540bedd43f5973cf3503b0aac04ee155e57dd205d0f4ae805ec2ee3724e38286473f1b02188af65d34b2d4.png)

**Comment by alsomanya** [comment]
Looks good to me! Will update original description in this ticket.
