### ISSUE TITLE
Users can see all their clients

### ISSUE THREAD

**Issue by alsomanya** [codeforamerica/clientcomm-rails#8]
**User story:**
- As a PO
- I want to see all of my clients and select one from a list
- So that I have an overview of my caseload, and I don't have to manually enter their contact information every time I want to message them
 
**Requirements:**
- Client name, timestamp of last contact, new message count (if applicable)
- Sorting by the user isn’t possible (for now)
- Default sorted by time of last message
- Desktop design: https://invis.io/4GBODKTUN#/233336022_Client_List_-_Simple
- Mobile design: https://invis.io/AXBODPK38

In the product brief: https://docs.google.com/document/d/1ZJ2fvgRJWKj4MQABRe2xqMiTg6K7q8VDOfDAkZX4qIo/edit#heading=h.atc2dlb771p6

**Comment by tmaybe** [comment]
Done as of 2c52d6c90f7dae46b85ae59b87e91590a5fc03eb

Users can not yet select a client from the list; that will come with the implementation of #9 and #10
