### ISSUE TITLE
Mark undelivered messages more prominently in the interface

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/clientcomm-rails#80]
It's easy to miss that a message hasn't been delivered in the interface; a case manager has to notice the status text under the message bubble:

![screen shot 2017-07-13 at 10 21 37 am](https://user-images.githubusercontent.com/546665/28179012-78374fbe-67b5-11e7-9232-c350204884ca.png)

Undelivered messages should be more differentiated from other messages so that case managers know there's an issue.

**Comment by racheledelman** [comment]
For now we can just use the form error state styling to make it more prominent. Later we can think about adding the option to try again.
![not delivered2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a2c1d4a9135c1300017b57/125516c66e82c728ace21e0d46e69b8e638686a586ffba51a159a2d665043761260ea62864c7b96aea1a2d025e0d1aaf14090a10fbfbdf23a6b639228c5b02e5c3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0eb3925e08e8a463b1d1755.png)
